options:
  merge-default-rules: true
files:
  include: 'projects/**/*.s[a,c]ss'
  ignore:
    - 'node_modules/'
rules:
  leading-zero:
    - 1
    - 'include': true
  class-name-format:
    - 0
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  placeholder-in-extend:
    - 0
  mixins-before-declarations:
    - 1
  no-vendor-prefixes:
    - 0
  no-css-comments:
    - 1
  no-misspelled-properties:
    - 1
    - 'extra-properties':
        - 'overflow-scrolling'
  property-sort-order:
    - 1
    - 'order': 'smacss'
  nesting-depth:
    - 1
    - 'max-depth': 3
  force-pseudo-nesting:
    - 0
  force-element-nesting:
    - 0
  no-qualifying-elements:
    - 1
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  attribute-quotes:
    - 1
  bem-depth:
    - 1
    - 'max-depth': 1
  border-zero:
    - 'convention': 0
  pseudo-element:
    - 1
